# Generated by Django 6.0.8 on 2026-08-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short descriptive name for this rule (e.g. Python Guide)', max_length=255)),
                ('keywords', models.TextField(help_text='Comma-separated trigger keywords (e.g. python, python guide)')),
                ('comment_reply', models.TextField(blank=True, default='Thanks! 👋 Check your DM.', help_text='Public comment reply text')),
                ('dm_message', models.TextField(blank=True, default='Hey {{username}} 👋 Follow us and reply DONE to receive the resource.', help_text='Initial DM message text')),
                ('confirmation_keyword', models.CharField(default='DONE', help_text='Keyword user sends to get final resource', max_length=64)),
                ('final_message', models.TextField(blank=True, default='Awesome! 🎉 Here is your guide: {{resource_url}}', help_text='Final DM text containing resource link')),
                ('resource_url', models.URLField(blank=True, default='', help_text='URL of resource/guide to send', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment & DM Automation',
                'verbose_name_plural': 'Comment & DM Automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('COMMENT', 'Comment Event'), ('MESSAGE', 'Message Event'), ('CONFIRMATION', 'Confirmation Keyword Event')], max_length=32)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='instaautomation.commentautomation')),
            ],
            options={
                'verbose_name': 'Automation Execution',
                'verbose_name_plural': 'Automation Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('username', models.CharField(db_index=True, max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_picture', models.URLField(blank=True, default='', max_length=1024)),
                ('account_type', models.CharField(blank=True, default='BUSINESS', max_length=64)),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('TOKEN_EXPIRED', 'Token Expired'), ('REAUTH_REQUIRED', 'Reauth Required'), ('ERROR', 'Error')], default='CONNECTED', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connection_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commentautomation',
            name='instagram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='instaautomation.instagramaccount'),
        ),
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(db_index=True, max_length=128)),
                ('participant_username', models.CharField(blank=True, default='', max_length=128)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('awaiting_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to='instaautomation.commentautomation')),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='instaautomation.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram Conversation',
                'verbose_name_plural': 'Instagram Conversations',
                'ordering': ['-last_message_at'],
                'unique_together': {('instagram_account', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sender_id', models.CharField(max_length=128)),
                ('message_text', models.TextField()),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instaautomation.instagramconversation')),
            ],
            options={
                'verbose_name': 'Instagram Message',
                'verbose_name_plural': 'Instagram Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
