# Generated by Django 6.0.8 on 2026-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaautomation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentautomation',
            name='require_follow',
            field=models.BooleanField(default=True, help_text='Check if user is following before sending link. If not following, ask them to follow first!'),
        ),
        migrations.AddField(
            model_name='commentautomation',
            name='specific_reel_id',
            field=models.CharField(blank=True, default='', help_text='Optional Instagram Reel URL or Media ID (e.g. https://www.instagram.com/reel/C123...)', max_length=255),
        ),
        migrations.AddField(
            model_name='commentautomation',
            name='target_scope',
            field=models.CharField(choices=[('ALL_REELS', 'All Reels & Posts'), ('SPECIFIC_REEL', 'Specific Reel / Post Only')], default='ALL_REELS', help_text='Apply to all reels or a specific reel URL/ID', max_length=32),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='comment_reply',
            field=models.TextField(blank=True, default='Thanks! 👋 I just sent you a DM.', help_text='Public comment reply text'),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='confirmation_keyword',
            field=models.CharField(default='DONE', help_text='Keyword user sends after following (e.g. DONE)', max_length=64),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='dm_message',
            field=models.TextField(blank=True, default="Hey {{username}} 👋 Thanks for your comment! Make sure you follow @{{account_username}} and reply 'DONE' to get the link.", help_text='Initial DM message text'),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='final_message',
            field=models.TextField(blank=True, default='Awesome! 🎉 Here is your direct link: {{resource_url}}', help_text='Final DM text containing resource link'),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='keywords',
            field=models.TextField(help_text='Comma-separated trigger keywords (e.g. python, guide, link)'),
        ),
        migrations.AlterField(
            model_name='commentautomation',
            name='name',
            field=models.CharField(help_text='Short descriptive name for this rule (e.g. Python Guide Reel)', max_length=255),
        ),
    ]
