# Generated by Django 6.0.8 on 2026-08-05 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Program', max_length=255)),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript (Node.js/V8)'), ('java', 'Java 17')], default='python', max_length=20)),
                ('code', models.TextField(help_text='Source code for execution and debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebugSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='python', max_length=20)),
                ('code', models.TextField()),
                ('breakpoints', models.JSONField(default=list, help_text='List of line numbers set as breakpoints')),
                ('total_steps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debug_sessions', to='debugger.codesnippet')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionTraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(help_text='0-indexed step sequence in execution timeline')),
                ('line_number', models.IntegerField(help_text='Currently executing line number in source code')),
                ('line_text', models.CharField(blank=True, max_length=512)),
                ('event_type', models.CharField(default='line', help_text='line, call, return, or exception', max_length=30)),
                ('stack_frames', models.JSONField(default=list, help_text='Call stack representation [main() -> fn()]')),
                ('variables', models.JSONField(default=dict, help_text='Variables state with types, values, & simulated memory pointers')),
                ('heap_objects', models.JSONField(default=dict, help_text='Heap memory graph for lists, dicts, objects, & references')),
                ('stdout', models.TextField(blank=True, help_text='Cumulative standard output stream at this step')),
                ('ai_explanation', models.TextField(blank=True, help_text='Beginner-friendly explanation of what happened in this step')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_steps', to='debugger.debugsession')),
            ],
            options={
                'ordering': ['step_index'],
                'unique_together': {('session', 'step_index')},
            },
        ),
    ]
