# Generated by Django 6.0.8 on 2026-08-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='zap', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('budget_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Per Hour'), ('NEGOTIABLE', 'Negotiable')], default='FIXED', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Standard (24h+)'), ('MEDIUM', 'Urgent (Today)'), ('HIGH', 'ASAP / High Priority')], default='MEDIUM', max_length=20)),
                ('location', models.CharField(default='Remote', max_length=150)),
                ('is_remote', models.BooleanField(default=True)),
                ('poster_name', models.CharField(max_length=100)),
                ('poster_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirements.category')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfiller_name', models.CharField(max_length=100)),
                ('fulfiller_email', models.EmailField(max_length=254)),
                ('quote_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery', models.CharField(default='Today', max_length=100)),
                ('pitch_message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='requirements.requirement')),
            ],
        ),
    ]
