# Generated by Django 6.0.8 on 2026-08-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='briefcase', max_length=50),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Software Engineer Intern - Summer 2026', max_length=200)),
                ('company_name', models.CharField(help_text='e.g. Google, Stripe, TechCorp', max_length=150)),
                ('company_logo_icon', models.CharField(default='building', help_text='Icon key or logo URL', max_length=50)),
                ('job_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-Time Job'), ('PART_TIME', 'Part-Time Job'), ('FREELANCE', 'Freelance / Contract'), ('CAMPUS', 'Campus Drive')], default='INTERNSHIP', max_length=20)),
                ('stipend_salary', models.CharField(help_text='e.g. $2,500/mo or $85,000/yr', max_length=100)),
                ('location', models.CharField(default='Remote', max_length=150)),
                ('is_remote', models.BooleanField(default=True)),
                ('skills_required', models.CharField(help_text='Comma-separated skills e.g. Python, React, SQL', max_length=300)),
                ('apply_url', models.URLField(blank=True, help_text='External application portal link', max_length=500, null=True)),
                ('allow_direct_apply', models.BooleanField(default=True, help_text='Allow students to apply directly on platform')),
                ('description', models.TextField(help_text='Detailed job description and key responsibilities')),
                ('eligibility', models.TextField(blank=True, default='Open to all students', help_text='Batch, GPA, or degree requirements')),
                ('posted_by', models.CharField(default='Campus Hiring Team', max_length=100)),
                ('poster_email', models.EmailField(default='recruiter@company.com', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Accepting Applications'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(help_text='Application closing date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='requirements.category')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(blank=True, default='', max_length=30)),
                ('degree_major', models.CharField(default='B.Tech Computer Science', max_length=100)),
                ('graduation_year', models.CharField(default='2026', max_length=10)),
                ('resume_url', models.URLField(help_text='Google Drive or Cloud Resume URL', max_length=500)),
                ('github_linkedin', models.URLField(blank=True, default='', max_length=500)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Not Selected')], default='SUBMITTED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='requirements.jobposting')),
            ],
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
