# Generated by Django 6.0.8 on 2026-08-05 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_remove_requirement_category_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date this requirement was posted (editable). Defaults to today.'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='allow_direct_apply',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Official external application link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo_icon',
            field=models.CharField(default='building', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(help_text='e.g. Stripe, Vercel, Microsoft', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(help_text='Automatically set to 3 days after posting'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(help_text='Detailed job description and responsibilities'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='eligibility',
            field=models.TextField(blank=True, default='Open to all students'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_by',
            field=models.CharField(default='Kashii Updatez Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='poster_email',
            field=models.EmailField(default='admin@kashiiupdatez.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (Accepting Applications)'), ('EXPIRED', 'Deactivated / Expired (3-Day Auto-Closed)'), ('CLOSED', 'Manually Closed')], default='ACTIVE', max_length=20),
        ),
    ]
