# Generated by Django 6.0.8 on 2026-08-05 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_add_posted_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
