# Generated by Django 6.0.8 on 2026-08-05 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_jobposting_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
