# Generated by Django 6.0.8 on 2026-08-05 16:09

import uuid
from django.db import migrations, models


def gen_unique_uuids(apps, schema_editor):
    JobPosting = apps.get_model('requirements', 'JobPosting')
    for job in JobPosting.objects.all():
        job.uuid = uuid.uuid4()
        job.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_jobposting_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_unique_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jobposting',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
