# Generated by Django 6.0.8 on 2026-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_alter_jobposting_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='General Inquiry', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('topic', models.CharField(choices=[('PYTHON', 'Python Programming'), ('DJANGO', 'Django & Web Development'), ('CAREER', 'Student Career & Roadmaps'), ('DSA', 'Data Structures & Algorithms'), ('INTERVIEW', 'Interview Preparation'), ('DEBUGGER', 'Debugging & Code Analysis')], default='PYTHON', max_length=30)),
                ('summary', models.TextField(help_text='Concise 2-3 sentence overview for SEO meta descriptions.')),
                ('content', models.TextField(help_text='Full rich long-form tutorial/article body.')),
                ('read_time', models.CharField(default='8 min read', max_length=30)),
                ('author_name', models.CharField(default='Kashinath (Kashii)', max_length=100)),
                ('author_avatar', models.CharField(default='/static/images/kashii-author.jpg', max_length=250)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], default='PUBLISHED', max_length=20)),
                ('tags', models.CharField(default='Python, Career, Freshers', max_length=250)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide & Tutorial',
                'verbose_name_plural': 'Guides & Tutorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(help_text='Automatically set to 7 days after posting'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (Accepting Applications)'), ('EXPIRED', 'Deactivated / Expired (7-Day Auto-Closed)'), ('CLOSED', 'Manually Closed')], default='ACTIVE', max_length=20),
        ),
    ]
