# Generated by Django 6.0.8 on 2026-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_contactinquiry_guidearticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidearticle',
            name='pdf_download_url',
            field=models.URLField(blank=True, default='', help_text='Google Drive download/view link for PDF study notes.', max_length=500),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='pdf_file_name',
            field=models.CharField(blank=True, default='', help_text='e.g. ADVANCED PYTHON BY KASHINATH.pdf', max_length=150),
        ),
    ]
