# Generated by Django 6.1 on 2026-08-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_guidearticle_pdf_download_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 🔥 Top 5 IT Drives Today - Aug 2026', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('banner_tag', models.CharField(default='🔥 DAILY MEGA HIRING DRIVE', help_text='Header badge e.g. 💼 DELOITTE SPECIAL', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional summary of this requirement collection')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='groups', to='requirements.jobposting')),
            ],
            options={
                'verbose_name': 'Requirement Group / Bundle',
                'verbose_name_plural': 'Requirement Groups / Bundles',
                'ordering': ['-created_at'],
            },
        ),
    ]
