# Generated by Django 6.1 on 2026-08-25
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_jobgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroup',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Automatically set to 7 days after creation', null=True),
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date this drive group was posted. Defaults to today.'),
        ),
    ]
