# Generated by Django 6.1 on 2026-08-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0009_jobgroup_7day_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='selection_process',
            field=models.TextField(blank=True, default='', help_text='Step-by-step interview selection rounds e.g. Round 1: Online Aptitude -> Round 2: Technical Interview -> Round 3: HR'),
        ),
    ]
