# Generated by Django 6.1 on 2026-08-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0010_jobposting_selection_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='study_materials',
            field=models.JSONField(blank=True, default=list, help_text='List of free study material links with title, desc, and url'),
        ),
    ]
