# Generated by Django 6.1 on 2026-08-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0011_jobposting_study_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(db_index=True, help_text='SHA-256 hash of IP + User-Agent for unique visitor counting', max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.CharField(db_index=True, default='Direct', max_length=100)),
                ('referrer_raw', models.CharField(blank=True, default='', max_length=500)),
                ('device_type', models.CharField(db_index=True, default='Desktop', max_length=20)),
                ('browser', models.CharField(default='Other', max_length=50)),
                ('os', models.CharField(default='Other', max_length=50)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address_masked', models.CharField(blank=True, default='', max_length=45)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['timestamp', 'is_bot'], name='req_sv_time_bot_idx'),
                    models.Index(fields=['visitor_hash', 'timestamp'], name='req_sv_hash_time_idx'),
                    models.Index(fields=['path', 'timestamp'], name='req_sv_path_time_idx'),
                ],
            },
        ),
    ]
