# Generated by Django 6.0.8 on 2026-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_sitevisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='requirement_timesta_1fc0a4_idx',
            old_name='req_sv_time_bot_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='requirement_visitor_8292d9_idx',
            old_name='req_sv_hash_time_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='requirement_path_f23d46_idx',
            old_name='req_sv_path_time_idx',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_by',
            field=models.CharField(blank=True, default='Kashii Updatez Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='poster_email',
            field=models.EmailField(blank=True, default='admin@kashiiupdatez.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills_required',
            field=models.TextField(default='Problem Solving, Software Engineering', help_text='Comma-separated skills e.g. Python, React, SQL'),
        ),
    ]
