# Generated by Django 6.0.8 on 2026-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0014_ensure_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_date', '-created_at'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='banner_tag',
            field=models.CharField(default='🔥 KASHIIUPDATEZ TECH DRIVE', help_text='Header badge e.g. 🔥 KASHIIUPDATEZ TECH DRIVE', max_length=100),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', '-posted_date', '-created_at'], name='requirement_status_00ff24_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['category', 'status', '-posted_date'], name='requirement_categor_1148a7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['uuid'], name='requirement_uuid_ba3e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posted_date'], name='requirement_posted__f59336_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company_name'], name='requirement_company_0b5141_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', 'deadline'], name='requirement_status_e1f390_idx'),
        ),
    ]
