# Generated by Django 6.0.8 on 2026-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0015_alter_jobposting_options_alter_jobgroup_banner_tag_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['is_bot', 'timestamp'], name='requirement_is_bot_1273fe_idx'),
        ),
    ]
