# Generated by Django 6.0.8 on 2026-08-13 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Rule Title (e.g. Python Job Link DM)', max_length=200)),
                ('target_scope', models.CharField(choices=[('ALL_REELS', 'All Reels & Posts'), ('SPECIFIC_REEL', 'Specific Reel / Post')], default='ALL_REELS', max_length=20)),
                ('reel_url_or_id', models.CharField(blank=True, help_text='Target Instagram Reel URL or Media ID (if SPECIFIC_REEL)', max_length=300, null=True)),
                ('trigger_keyword', models.CharField(help_text='Comment keyword to trigger automation (e.g. python, link, job)', max_length=100)),
                ('comment_reply_text', models.TextField(help_text='Public comment reply template (use {username} for dynamic tag)')),
                ('private_dm_text', models.TextField(help_text='Private DM message body')),
                ('resource_url', models.URLField(blank=True, help_text='Resource link included in DM / follow gate', null=True)),
                ('enforce_follower_gate', models.BooleanField(default=True, help_text='Require user to follow account before delivering link')),
                ('follower_gate_message', models.TextField(default="Thanks for your comment! 👋 Please follow @{account_username} and reply 'DONE' to get your instant direct access link!", help_text='Message sent if user is not following')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Meta Page / Instagram User ID', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Instagram Account Handle (e.g. @pythonkashi)', max_length=150)),
                ('page_access_token', models.TextField(help_text='Meta Page Long-Lived User Access Token')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment_id', models.CharField(max_length=150)),
                ('commenter_username', models.CharField(max_length=150)),
                ('commenter_id', models.CharField(blank=True, max_length=150, null=True)),
                ('media_id', models.CharField(blank=True, max_length=150, null=True)),
                ('comment_text', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success - DM Delivered'), ('GATE_SENT', 'Follower Gate Sent'), ('FAILED', 'Execution Failed'), ('IGNORED', 'Keyword Not Matched')], default='SUCCESS', max_length=20)),
                ('response_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='instagram.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='automationrule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='instagram.instagramaccount'),
        ),
    ]
