# Generated by Django 6.0.8 on 2026-08-13 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('reel_id', models.CharField(blank=True, help_text='Specific Reel ID or leave empty for all reels', max_length=255, null=True)),
                ('trigger_type', models.CharField(choices=[('ANY_COMMENT', 'Any Comment'), ('KEYWORD', 'Keyword')], default='KEYWORD', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REPLY_COMMENT', 'Reply to Comment'), ('SEND_DM', 'Send Direct Message')], max_length=50)),
                ('configuration', models.JSONField(default=dict, help_text='Stores messages, reply variations, links, variables')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='instagram.automation')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('CONTAINS', 'Contains Keyword'), ('EXACT', 'Exact Match')], default='CONTAINS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='instagram.automation')),
            ],
        ),
        migrations.CreateModel(
            name='CommentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_comment_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_events', to='instagram.automation')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=50)),
                ('response', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='instagram.automationaction')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='instagram.automation')),
                ('comment_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='instagram.commentevent')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='automation',
            name='instagram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='instagram.instagramaccount'),
        ),
    ]
